### ISSUE TITLE
Groovy Conflicting Module Error 

### ISSUE THREAD

**Issue by bwagner5** [noamt/elasticsearch-grails-plugin#110]
<strong>I'm using Grails 2.5.0 (runtime ":elasticsearch:0.0.4.4") and am getting a conflicting module error when deploying my application in a .war file. grails run-app works fine , run-war does not work (doesn't matter if I use Development or Production environment).</strong>

| Error java.lang.ExceptionInInitializerError
| Error 	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:61)
| Error 	at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
| Error 	at org.codehaus.groovy.grails.commons.AbstractGrailsApplication.<init>(AbstractGrailsApplication.java:45)
| Error 	at org.codehaus.groovy.grails.commons.DefaultGrailsApplication.<init>(DefaultGrailsApplication.java:95)
| Error 	at org.codehaus.groovy.grails.commons.DefaultGrailsApplication.<init>(DefaultGrailsApplication.java:91)
| Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
| Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
| Error 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
| Error 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
| Error 	at java.lang.Class.newInstance(Class.java:438)
| Error 	at org.codehaus.groovy.grails.plugins.log4j.web.util.Log4jConfigListener.createGrailsApplication(Log4jConfigListener.java:54)
| Error 	at org.codehaus.groovy.grails.plugins.log4j.web.util.Log4jConfigListener.contextInitialized(Log4jConfigListener.java:42)
| Error 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4992)
| Error 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5490)
| Error 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
| Error 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
| Error 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
| Error 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
| Error 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
| Error 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
| Error 	at java.lang.Thread.run(Thread.java:745)
| Error Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-all is loaded in version 2.4.3 and you are trying to load version 2.3.7
| Error 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:509)
| Error 	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:77)
| Error 	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromMetaInf(ExtensionModuleScanner.java:71)
| Error 	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModules(ExtensionModuleScanner.java:53)
| Error 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:110)
| Error 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:71)
| Error 	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:33)
| Error 	... 21 more
Exception sending context initialized event to listener instance of class org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener
java.lang.NoClassDefFoundError: Could not initialize class groovy.lang.GroovySystem
	at groovy.lang.ExpandoMetaClassCreationHandle.enable(ExpandoMetaClassCreationHandle.java:74)
	at groovy.lang.ExpandoMetaClass.enableGlobally(ExpandoMetaClass.java:464)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:57)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4992)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5490)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bwagner5** [comment]
This can be solved by putting an excludes block for groovy-all in the plugin dependency block. 

        runtime ":elasticsearch:0.0.4.4", {
            excludes 'groovy-all'
        }

**Comment by donbeave** [comment]
Fixed https://github.com/noamt/elasticsearch-grails-plugin/pull/103, but not released yet.

**Comment by zaccak** [comment]
I'm getting the same issue, looking forward for a release but I'll use the workaround for now.
Thanks!

**Comment by noamt** [comment]
Try 0.0.4.5

**Comment by valerius** [comment]
+1
