### ISSUE TITLE
Searching over multiple domain classes

### ISSUE THREAD

**Issue by sophiaraw** [noamt/elasticsearch-grails-plugin#111]
I have 5 domain classes that are searchable, but sometimes I only want to search over 2 of them. How would I write that query?

Currently I search over all 5 like this:
        def res = elasticSearchService.search([searchType:'dfs_query_and_fetch']) {
                bool {
                    must {
                        query_string(query: searchString)
                    }
                    must {
                        terms(companyId: companyIds, minimum_should_match: 1)
                    }
                }
                null
            }

I would like to use the same query but only over 2 [Task, Project]

**Comment by sircelsiussexy** [comment]
Hi,

The `search` method has a `Map params` parameter. You can specify in that Map the types you want to query.

Example:

```
  def res = elasticSearchService.search([searchType: 'dfs_query_and_fetch', types: ['Task', 'Project']){
  // query
  }
```

See [`ElasticSearchServiceIntegrationSpec`](https://github.com/noamt/elasticsearch-grails-plugin/blob/master/test/integration/org/grails/plugins/elasticsearch/ElasticSearchServiceIntegrationSpec.groovy) for more examples.

**Comment by sophiaraw** [comment]
Perfect thank you

**Comment by sircelsiussexy** [comment]
Sure. 

@noamt @marcos-carceles feel free to close this.
