### ISSUE TITLE
Multi tenants

### ISSUE THREAD

**Issue by sophiaraw** [noamt/elasticsearch-grails-plugin#112]
I have a multi tenant application. Each tenant have its own config file where I specify the index name:
elasticSearch {
    index.name = 'tenantIndex'  // different name for each tenant
}

But when I search the results include hits from other tenants.

Please can you advise.

I use:
grails 2.3.11
elasticsearch:0.0.4.4

**Comment by sircelsiussexy** [comment]
Are you trying to query different indices during runtime? If so you can also specify it when searching via the `indices` entry of the `params` map. See the [search docs](http://noamt.github.io/elasticsearch-grails-plugin/ref/ElasticSearchService/search.html).

**Comment by sophiaraw** [comment]
Awesome, thanks

**Comment by ejaz-ahmed** [comment]
@sophiaraw  If it the answer your question, can you close this issue?

**Comment by puneetbehl** [comment]
@sophiaraw Can you please close this issue?

**Comment by puneetbehl** [comment]
BTW, here is the update link of [search docs](http://noamt.github.io/elasticsearch-grails-plugin/docs/index.html#searching)
