### ISSUE TITLE
No datastore implementation specified

### ISSUE THREAD

**Issue by bernji** [noamt/elasticsearch-grails-plugin#122]
Hello,

I created a new grails app and added elastic search as described in the manuals to the BuildConfig.

When I start I get the error:
No datastore implementation specified

I also tried:
elasticsearch {
  datastoreImpl = "hibernateDatastore"
}

but I am still getting the same error :(

Can you help?

**Comment by sufyanshoaib** [comment]
Seems to be case issue, check doc, its `elasticSearch`

**Comment by bernji** [comment]
I imported the springloaded jar 1.2.3 and it worked
