### ISSUE TITLE
Can't load data from DB (domain models) into Elasticsearch

### ISSUE THREAD

**Issue by daptordarattler** [noamt/elasticsearch-grails-plugin#124]
Hello,
I used the default configuration from the plugin docs and have a locally installed elasticsearch instance with default configurations. After trying the transport mode for so long only to come here to see a bug report that it doesn't work. 
Now I have tried both the node & dataNode modes and still not getting anywhere. The main problem is that I have kibana connected to my instance, and after running my app , it doesn't run at all, I think it gets hung up at the bootstrap stage with showing any errors, but keeps running in the background as if waiting to bind to localhost:8080. After waiting for almost an hour today for the app to start, I am convinced that I am either doing something wrong or there is a bug.

Using Grails 2.5.0, with elasticsearch-plugin v0.4.6 and elasticsearch v1.6.0, and Kibana 4 integration.

I am able to see that the shards are created when I access this URL http://localhost:9200/_cat/shards but then their size is 144b and this never changes no matter how long I wait. After quering the endpoints on elasticsearch it is quite obvious that there is not data in my instance.

I have no idea why this is happening, I have disableAutoIndex set to false, and bulkIndexOnStartup set to true.

Has anyone seen this before? Anyone know what is happening?

Any feedback will be greatly appreciated.

**Comment by puneetbehl** [comment]
Although this is a very old issue, I want to make sure that you have a clear path to using Elasticsearch plugin using latest [documentation](http://noamt.github.io/elasticsearch-grails-plugin/snapshot/index.html) as a reference.

**Comment by daptordarattler** [comment]
Yeah, i resolved this by using the property references in the documentation. but it would have been nice to have had an update 3 years ago when i started having the issue. Thanks

**Comment by puneetbehl** [comment]
@daptordarattler Thanks for the response. I understand your concern.
