### ISSUE TITLE
General Search Controller and View?

### ISSUE THREAD

**Issue by hansgru** [noamt/elasticsearch-grails-plugin#126]
Hi,

This plug-in is supposed to replace the Searchable plug-in https://github.com/gpc/searchable (since Searchable is based on Compass).

Is there any migration path from Searchable to ElasticSearchGrails? 

I'm missing the General Search Controller and View present in the Searchable plug-ing: it ensured that the plug-in just needs to be specified in Config.groovy, the entities annotated and an app wide search was available right away.

Is there such a functionality in the ElasticSearchGrails plug-in? or is it in a separate plug-in/example/wiki whatsoever?

Thank you.

**Comment by sircelsiussexy** [comment]
As far as I know this plugin doesn't provide an app wide search view.

However all your classes marked as searchable (via the `searchable` property, see the [docs](http://noamt.github.io/elasticsearch-grails-plugin/guide/mapping.html)) should be searchable via either of the `Entity.search` and `ElasticSearchService.search` methods.
