### ISSUE TITLE
Grails 3 port

### ISSUE THREAD

**Issue by ejaz-ahmed** [noamt/elasticsearch-grails-plugin#127]
Is there any plan to port this plugin to grails 3?

**Comment by donbeave** [comment]
I have this plan.

**Comment by ejaz-ahmed** [comment]
Thanks @donbeave for the update. When should we expect this?

**Comment by donbeave** [comment]
I will try to publish it in October-November.

**Comment by donbeave** [comment]
@ejaz-ahmed hi! you can try this branch: https://github.com/donbeave/grails-elasticsearch/tree/grails3

**Comment by puneetbehl** [comment]
#144
