### ISSUE TITLE
Plugin installation error

### ISSUE THREAD

**Issue by hubix786** [noamt/elasticsearch-grails-plugin#140]
Hello, i have problem with installation plugin on Grails 2.4.4
Here's my log:

```
Loading Grails 2.4.4
|Configuring classpath

|Environment set to development
.................................
|Packaging Grails application
|Installing zip elasticsearch-0.0.4.6.zip...
...
|Installed plugin elasticsearch-0.0.4.6
The environment variable ELASTIC_SEARCH_HOME specifying the location of ElasticSearch is not set.
Please make sure this variable is set so that the ElasticSearch plugin scripts function correctly.

.....................
|Compiling 230 source files
.Error 
|
Fatal error during compilation org.apache.tools.ant.BuildException: java.lang.UnsupportedClassVersionError: org/elasticsearch/action/admin/cluster/health/ClusterHealthRequest : Unsupported major.minor version 51.0 (Use --stacktrace to see the full trace)
```

**Comment by puneetbehl** [comment]
I think the problem is you do not have path variable "ELASTIC_SEARCH_HOME" pointing to your ElasticSearch home directory.

**Comment by hubix786** [comment]
I installed ElasticSearch and set path variable, but i still have fatal error during compilation

**Comment by vonovak** [comment]
What version of elasticsearch are you using? Plugin only supports version
1.*
Am 02.02.2016 18:12 schrieb "hubix786" <notifications@github.com>:

**Comment by hubix786** [comment]
I installed the newest - 2.1.1. Which version would you recommend as best for cooperation with this plugin?

**Comment by vonovak** [comment]
The plugin was written with 1.6 which is probably the safest option, but
I'm running it with 1.7.4 and it works well - there were no api changes in
the features I'm using.
Am 04.02.2016 10:35 vorm. schrieb "hubix786" <notifications@github.com>:

**Comment by hubix786** [comment]
On ES 1.6 version still same error... now i really don't know what i'm doing wrong

**Comment by vonovak** [comment]
And did you change the home variable? This has to work. Make sure grails is
picking up the right elasticseach. Try grails clean or clean all if stuck.
Am 04.02.2016 11:22 vorm. schrieb "hubix786" <notifications@github.com>:

**Comment by hubix786** [comment]
every time i changed ES version i edited path variable. After cleaning log is diffrent and soooooooooo long

http://ctrlv.it/id/4217/1530353439

**Comment by vonovak** [comment]
hmm googling for the "Unsupported major.minor version 51.0" indeed brings up java-related stuff. I'm running latest oracle jdk (on ubuntu).

**Comment by hubix786** [comment]
some time ago i googled very similar query (with class name) and i saw that too. For programming purposes i have installed 3! jdk versions: 1.6, 1.7 and 1.8, and in environmental path i have set 1.8, maybe that make this error, although project vesion is 1.6.

**Comment by hubix786** [comment]
Case closed. major.minor version 51.0 refers to Java 1.7, so trying to start @ Java 1.6 creates this error. Thanks for help.
