### ISSUE TITLE
Plugin versioning

### ISSUE THREAD

**Issue by marcoscarceles** [noamt/elasticsearch-grails-plugin#141]
Hi there,

I'n planning to publish an update for the plugin for its Grails 2.x version so that it's compatible with Elasticsearch 2.1.2 (there's no 2.2.0 elastic-groovy support yet :( ). Since we're starting to have a bunch of incompatible versions of the plugin (Grails 3.x vs Grails 2.x, ES 1.x vs ES 2.x), I must raise the question of versioning...

So far I've versioned my branch as `0.1.x-SNAPSHOT`, I'd like to suggest the following versioning convention. Please let me know what you think:

`<GRAILS_VERSION>.<ES_VERSION>.<FEATURE/PATCH_VERSION>`, where there isn't really a 1-to-1 plugin version to grails or es version, but we just increase our major or minor version by one, whenever there are breaking changes on either Grails or ES. Therefore have something that looks like:

| Plugin Version        | Grails           | Elasticsearch |
| ------------- |:-------------:| -----:|
| 0.0.4      | 2.4.x | 1.x |
| 0.1.x      | 2.4.x      |   2.1.x |
| 0.2.x      | 2.4.x      |   2.2.x |
| 0.3.x      | 2.4.x      |   (hypothetical) 3.0 |
| 1.0.x | 3.1.x      |    1.x |
| 1.1.x | 3.1.x      |    2.1.x |
| 1.2.x | 3.1.x      |    2.2.x |
| 2.2.x | (hypothetical )3.2.x      |    2.2.x |
| 3.2.x | (hypothetical ) 4.0.x      |    2.2.x |

And so on...

What do you guys think?

**Comment by Schlogen** [comment]
@marcoscarceles Are there breaking changes in elasticsearch between say 2.1.x and 2.2.x ?

**Comment by Schlogen** [comment]
@marcoscarceles In general I think the versioning strategy you proposed, while detailed, is too complicated to be easily understood. Is it fair to say that elasticsearch 1.x is still widely used? Is it used enough to warrant being considered in the versioning strategy?

**Comment by marcoscarceles** [comment]
Hi @Schlogen I know it's complicated, but there are three different elements that will vary independently (grails, ES and the plugin itself) with incompatible apis and this is an aim to avoid locking users into specific provider versions. Suggestions for a cleaner way are more than welcome. About ES 1.x being supported, I totally agree and therefore the 0.0.x (which continues with the current versioning) and 1.0.x (for Grails 3) versions detailed above.

Looking forward to further feedback and suggestions!

**Comment by Schlogen** [comment]
@marcoscarceles What if the major and minor version of the plugin simply tracked the version of elasticsearch. I think we can consider any Grails 2.x work to be complete and will not be maintained. In addition, it's relatively rare for the version of Grails the plugin is created with impacts usage in other versions of Grails.

If there happens to be a breaking change, it would require users to do minor upgrades in their Grails version to take advantage of the new version of elasticsearch.

**Comment by marcoscarceles** [comment]
@Schlogen therefore...

| Plugin Version        | Grails           | Elasticsearch |
| ------------- |:-------------:| -----:|
| 0.0.4      | 2.4.x | 1.x |
| 0.1.x      | 2.4.x      |   2.1.x |
| 0.2.x      | 2.4.x      |   2.2.x |
| 2.1.x  | 3.x.x      |    2.1.x |
| 2.2.x  | 3.x.x      |    2.2.x |

Did I understand it right? Yup, that's totally fine by me.

I'd still like to release the 0.1 and 0.2, as these are being requested in #135 (plus 0.1 is already developed and available on #143 , since it's the scenario of one of my projects)

**Comment by puneetbehl** [comment]
ok, I am also good with @marcoscarceles suggestion and let's go with this.
