### ISSUE TITLE
indexing at startup blocking app startup?

### ISSUE THREAD

**Issue by tparkergh** [noamt/elasticsearch-grails-plugin#162]
I'm having a bit of a performance issue with indexing on startup and had a few questions regarding indexing and aliasing. I'm a little unclear about the startup index process.

 If I understand correctly, the app will attempt to index the data on startup if the appropriate flag is set, and will create a new versioned index if the appropriate flags are set and there is a change that requires a new index. During that process the app will continue to serve out reads from the old index while writing to the new index. If this is correct, the app should be fully started while the index is occurring.

What I think I'm seeing is the indexing occurring prior to the the grails application bootstrap, and seems to block the rest of the app from starting up. I'm running JBOSS and the startup script allows a set amount of time before giving up on the app. When I set the index on startup flag to true, the app doesn't start and the indexing takes 30-60 minutes (which I'm thinking is way too long). This wouldn't be an issue if the index builds in the background while the app starts up.

Any thoughts? I'm running an older version of elasticsearch-grails-pluging, v0.0.4.2. I will upgrade soon but not in a position to at the moment. I didn't see much in the release notes that would address these specific issues. 

Thanks
Tom

**Comment by tparkergh** [comment]
After rereading the doc, I'm wonder if I actually ever need to do a bulk index on startup if I want to use the aliasing strategy.

**Comment by marcoscarceles** [comment]
My recomendation on using the alias strategy would be not to reindex on start up but have another mechanism to allow reindexing in the background after the application starts (we use a quartz job for this).

The `elasticSearch.migration.disableAliasChange` configuration property was introduced with a set up similar to this in mind. application will be able to read from the `*_read` alias whilst its reindexing on the `*_write` alias. Your job should handle repointing the read alias to the write alias at the end of it with a code similar to.

`elasticSearchAdminService.pointAliasTo scm.queryingIndex, scm.indexName`

We've been using this configuration successfully in productions environments for two years now.

**Comment by tparkergh** [comment]
Thanks for getting back. 
I ended up turning off reindex on startup like you mentioned, then exposing a private service that would kick off the indexing when we needed it. We don't need to re-index regularly so the quartz job seems a bit overkill. And we would want to reindex at explicit moments when we make changes, such as a deploy that required a analyzer change or something that would impact indexing.

I kept the alias strategy the same. When it re-indexes. it will still create a new index and manage the read and write aliases. This seems to work fine. Though it would be nice if this didn't actually block startup. Seems like it doesn't need to.

In your above code, what is scm?

**Comment by marcoscarceles** [comment]
@tparkergh that another good way to achieve it, of course. We kept it blocking as the default behaviour to keep compatibility with older implementations of the plugin, but still configurable (as mentioned above) so you could follow an approach with multiple aliases for reading and writing (like yours) 😄
