### ISSUE TITLE
How to sort, limit and order search and searchResults?

### ISSUE THREAD

**Issue by PatrickHuetter** [noamt/elasticsearch-grails-plugin#166]
I'm using the search(String) method¹ (injected into the DomainClass) to search documents by lucene query syntax and i would like to add some filtering/querying features to my restful api. 

E.g. I've the rest call GET /persons which returns all persons, i would like to be able to filter this persons on their attributes. E.g.  GET /persons?q={luceneQuery}

I've already build this as described but now i need the possibility to sort, limit and order the persons. Maybe also to paginate, so that an offset is needed.
How would you implement this using this plugin? Maybe i should switch to query closures? Or is it possible to extend the query-strings method with some sort, order and limit features?

I'm using grails 3.1.9.

Best regards

¹ http://noamt.github.io/elasticsearch-grails-plugin/docs/index.html#queryStrings

**Comment by marcoscarceles** [comment]
Query Closures or `QueryBuilder` could provide you more control over the query. For your use case you can use `elasticSearchService` in combination with `SortBuilders` as described here:

http://noamt.github.io/elasticsearch-grails-plugin/docs/index.html#sorting

If you need finest grain control you can use the `elasticSearchHelper.withElasticSearch { Client client -> ... }` implementation using Elasticsearch API's.

**Comment by puneetbehl** [comment]
Here is how you can achieve it: 

```groovy

import esdemo.Post
import org.elasticsearch.search.sort.SortBuilder
import org.elasticsearch.search.sort.SortBuilders
import org.elasticsearch.search.sort.SortOrder

SortBuilder sortBuilder = SortBuilders.fieldSort('subject').order(SortOrder.DESC)

Post.search('xyz', [ indices: Post, types: Post, sort: sortBuilder, from: 0, size: 2 ])

```
