### ISSUE TITLE
problem with includeTransients in grails 3.2.0.RC1

### ISSUE THREAD

**Issue by rkimaoui** [noamt/elasticsearch-grails-plugin#176]
Hello there,

i have indexing errors when includeTransients=true in grails 3.2.0.RC1.
When i set includeTransients=false, it works well.
And It happened only when i upgraded from grails 3.0 to 3.2.

This is the error:
`ERROR grails.plugins.elasticsearch.index.IndexRequestQueue - Failed bulk item: MapperParsingException[object mapping for [message] tried to parse field [creatorId] as object, but got EOF, has a concrete value been provided to it?]`

> I don't have transients in my domain message

Thx in advance.

**Comment by puneetbehl** [comment]
@rkimaoui Could you please share sample application describing the problem as I am able to run fine with Grails 3.2.0.RC1 and with following example: 

_Anagram.groovy_
```groovy
package esdemo32

class Anagram {

    String original

    String getReverse() {
        original.reverse()
    }

    int getLength() {
        return original.length()
    }

    Boolean getPalindrome() {
        original == reverse
    }

    static transients = ['reverse', 'length', 'palindrome']

    static searchable = true
}

```
_Bootstrap.groovy_
```groovy
import esdemo32.Anagram

class BootStrap {

    def init = { servletContext ->
		new Anagram(original: "unbelievable").save(flush: true)
    }
    def destroy = {
    }
}
```

And, when I run following search it works fine:
```groovy
Anagram.search("elbaveilebnu")
```

**Comment by puneetbehl** [comment]
@rkimaoui any updates?

**Comment by puneetbehl** [comment]
Please feel free to re-open if the issue still persists with `v2.4.0`
