### ISSUE TITLE
cannot connect to mongodb with mongodb plugin of grails

### ISSUE THREAD

**Issue by hisou** [noamt/elasticsearch-grails-plugin#195]
I am using both elasticsearch plugins and mongodb plugins in my grails project. 
`compile "org.grails.plugins:elasticsearch:1.0.0"`
`compile 'org.grails.plugins:mongodb:6.1.1'`

The application.yml file is like:
`mongodb:`
`    host: "localhost"`
`    port: 27017`
`    databaseName: "search"`

`elasticSearch:`
`    client:`
`        mode: local`
   ` disableAutoIndex: false`
`    datastoreImpl: mongoDatastore`
`    bulkIndexOnStartup: true`
`    index:`
`        store.type: mmapfs`
I commented out the hibernate in build.grdle because I need to use mongodb as your primary datastore.

`//compile "org.grails.plugins:hibernate4"`
`//compile "org.hibernate:hibernate-ehcache"`
Then the mongodb worked well since I could use

`MyDomain.findByXXXXX()`
to query the data in my mongodb. 
But when I used

`def result = MyDomain.search("${query}") `
or
`def result = elasticSearchService.search("${query}")`
and print the result, it showed

`[total:0, searchResults:[]]`
That seemed the elasticSearch plugins worked but it did not connect to the mongodb.
I wonder whether datastoreImpl: mongoDatastore worked or not.

Is there something I am missing? Appreciate your help in advance.

Thank You

**Comment by HardikModha** [comment]
What is the status of elastic search index? By default elastic search binds port 9300 when running locally. So, When the grails server is running you can hit `http://localhost:9300/_cat/indices` to see whether the index was actually created or not.
