### ISSUE TITLE
bulk index in large number of data will stop indexing at some point

### ISSUE THREAD

**Issue by shsongtao1988** [noamt/elasticsearch-grails-plugin#213]
Using Grails 3.2.9 Elasticsearch 5.4.1 and plugin 1.4.1 ,while setting bulkIndexOnStartup : true and maxBulkRequest : 1000 , my data can be indexed into es ,but when the total data number is up to 420000 lines, the index will only indexes about 60000 lines, and then the cpu is up to 100% and no more data indexed. After some time , the program will hit a OOM error :  Java heap space .  I start the program with spring boot and tomcat embeded.  I tried to  change the java heap size but does not work . So what can I do to index all the data ?

**Comment by shsongtao1988** [comment]
ok, when i reduce the maxBulkRequest i can index more data , but i free the speed is very slow , any one can help me with the problem ?!

**Comment by shsongtao1988** [comment]
I tried to reduce the maxBulkRequest  number to 10, but when I indexed about 70000 lines , the same problem comes,  will the problem solved after I set the maxBulkRequest  limit to 1 ? That must be a long time to index all the 420000 lines data .

**Comment by shsongtao1988** [comment]
I think the index service some where maybe exists Memory Leak . But I don't know how to solve it .

**Comment by kdpeders** [comment]
Could this be because Grails 3 used Controllers/Services scoped as Singleton?  ElasticSearchService has property indexRequestQueue that may not ever get cleared then and could be the source of a memory leak.

**Comment by shsongtao1988** [comment]
well , I tried this ,using grails.controllers.defaultScope = session ,but still OOM  ,now I tried to bulk data through python ,using pymongo and elasticsearch. this need to do additional work .

**Comment by puneetbehl** [comment]
@shsongtao1988 Please share the sample application or the heap dump when you see OOM error. Also share the output of following command:
```bash
curl -XGET 'http://localhost:9200/_segments'
```

**Comment by puneetbehl** [comment]
@shsongtao1988  Any updates on this?
