### ISSUE TITLE
When will support Grails 3.3.3 + Elasticsearch 1.6

### ISSUE THREAD

**Issue by forestwanglin** [noamt/elasticsearch-grails-plugin#223]
Thanks in advance.

**Comment by puneetbehl** [comment]
I would recommend updating Elasticsearch. We currently support Grails 3 with Elasticsearch 5.4.3 and will work on supporting latest version of Elasticsearch.

**Comment by forestwanglin** [comment]
thx, i will try to update es.


| |
Forest
邮箱：forest_wanglin@163.com
|

签名由 网易邮箱大师 定制

On 04/01/2018 20:46, Puneet Behl wrote:

I would recommend updating Elasticsearch. We currently support Grails 3 with Elasticsearch 5.4.3 and will work on supporting latest version of Elasticsearch.
