### ISSUE TITLE
better search documentation

### ISSUE THREAD

**Issue by musketyr** [noamt/elasticsearch-grails-plugin#31]
the documentation for groovy dsl in elastic search is very brief. it would be nice if the plugin documentation would go further than just showing `bool { must { query_string }}`

**Comment by puneetbehl** [comment]
Following is the latest version of Documentation:
http://guides.grails.org/grails-elasticsearch/guide/index.html

In addition, there is a separate [Elasticsearch Grails Guide](http://guides.grails.org/grails-elasticsearch/guide/index.html) to start quickly with ES.
