### ISSUE TITLE
GeoPoint field in component object not sent to ElasticSearch as required 

### ISSUE THREAD

**Issue by kmalhotra** [noamt/elasticsearch-grails-plugin#69]
We are facing a problem when the Domain instance is unmarshalled and JSON object is sent to ElasticSearch for a PUT request.

Environment :- Grails 2.2.4 , ElasticSearch 1.2.4 , ElasticSearch Grails Plugin 0.0.3.3
Example structure:-
Domain A{
..
GeoPoint location   // Geopoint field location for Domain A
DomainB domainB

static embedded = ['location']
static searchable = {
domainB component: 'inner'
location geoPoint: true , component: 'inner' 
}
} 

Domain B{
...
GeoPoint geoPoint  // GeoPoint field for Domain B
static embedded = ['geoPoint']
static searchable ={
geoPoint geoPoint: true
}
}

class GeoPoint {
	Double lat
	Double lon
	static searchable = {
		except = ['class', 'id']
		root false
	}
}

When instance of DomainB is sent to ElasticSearch, geoPoint field is translated as {lat: 36.5, lon: 77.5} whereas if an Instance of DomainA is sent, geoPoint field of DomainB is translated as {id: null, class: package.GeoPoint, lat: 36.5, lon: 77.5} which is causing the following error:-
Caused by: org.elasticsearch.ElasticsearchParseException: field must be either 'lat', 'lon' or 'geohash'

Investigating into the source code of the plugin, issue seems to be with the DeepDomainClassMarshaller.

if (DomainClassArtefactHandler.isDomainClass(propertyClass)) {
String searchablePropertyName = getSearchablePropertyName()
if (propertyValue.class."$searchablePropertyName") {
// todo fixme - will throw exception when no searchable field.
marshallingContext.lastParentPropertyName = prop.name
if(propertyMapping?.isGeoPoint())// geopoint check added
marshallResult += [(prop.name): (marshallingContext.delegateMarshalling(propertyValue, propertyMapping.maxDepth))]
else
marshallResult += [(prop.name): ([id: propertyValue.ident(), 'class': propertyClassName] + marshallingContext.delegateMarshalling(propertyValue, propertyMapping.maxDepth))]
} else {
marshallResult += [(prop.name): [id: propertyValue.ident(), 'class': propertyClassName]]
}
}

Let me know in case further details are required. Also, suggest if there are any workarounds for this with 0.0.3.3.

Thanks in Advance.

**Comment by polydectes** [comment]
I am also having this problem and have already followed the details in stackoverflow as posted by sircelsiussexy.

It appears this is a problem with nesting of objects within the mappings.

We have the following classes:

class GeoPoint {
    Double lat
    Double lon
    static searchable = {
        only = ['lat','lon']
        root false
    }
}

class Address {
     // {additional address fields removed for compactness}.
    GeoPoint location
    static searchable = {
        root true
        location geoPoint: true, component: true
    }
}

class Organization {
    // {additional organization fields like "name" removed for compactness}.
    Address address
    static searchable = {
        root true
        address component: true
    }
}


When we create a new Address instance, everything appears to be working properly.  Data is added and it is locatable.

When we create a new Organization instance, we receive the exception:

[org.grails.plugins.elasticsearch.index.IndexRequestQueue :  : ] Failed bulk item: MapperParsingException[failed to parse]; nested: ElasticsearchParseException[field must be either 'lat', 'lon' or 'geohash']; 

We are running version 0.3.8 of the plugin with Grails 2.3.4 and a 'hibernateDataStore' in a development environment with client.mode = 'local'.

All recommendations for fixing this problem are appreciated.

**Comment by kmalhotra** [comment]
I have managed to fix this with few lines of coded added to "DeepDomainClassMarshaller.groovy" and overriding this file. 

Previous code:-
if (DomainClassArtefactHandler.isDomainClass(propertyClass)) {
                String searchablePropertyName = getSearchablePropertyName()
                if (propertyValue.class."$searchablePropertyName") {
                    // todo fixme - will throw exception when no searchable field.
                    marshallingContext.lastParentPropertyName = prop.name
                    marshallResult += [(prop.name): ([id: propertyValue.ident(), 'class': propertyClassName] + marshallingContext.delegateMarshalling(propertyValue, propertyMapping.maxDepth))]
                } else {
                    marshallResult += [(prop.name): [id: propertyValue.ident(), 'class': propertyClassName]]
                }

                // Non-domain marshalling
            }

New Code:-
if (DomainClassArtefactHandler.isDomainClass(propertyClass)) {
				String searchablePropertyName = getSearchablePropertyName()
				if (propertyValue.class."$searchablePropertyName") {
					// todo fixme - will throw exception when no searchable field.
					marshallingContext.lastParentPropertyName = prop.name
					if(propertyMapping?.isGeoPoint())
						marshallResult += [(prop.name): (marshallingContext.delegateMarshalling(propertyValue, propertyMapping.maxDepth))]
					else
						marshallResult += [(prop.name): ([id: propertyValue.ident(), 'class': propertyClassName] + marshallingContext.delegateMarshalling(propertyValue, propertyMapping.maxDepth))]
				} else {
					marshallResult += [(prop.name): [id: propertyValue.ident(), 'class': propertyClassName]]
				}

				// Non-domain marshalling
			}

Let me know in case issue still persists.

Note:- I am still using elasticsearch:0.0.3.3.

**Comment by sircelsiussexy** [comment]
@polydectes did you manage to solve your problem? If so how? I tried recreating the problem on a clean prokect but couldn't get it to work.

**Comment by jako512** [comment]
I can confirm kmalhotra's fix work and I have created pull request #90
