### ISSUE TITLE
Support for Using FilterBuilder

### ISSUE THREAD

**Issue by blaketastic2** [noamt/elasticsearch-grails-plugin#83]
It appears that there is no way to use the FilterBuilder as the filter instance. QueryBuilder is supported for the query, so it makes sense to allow for FilterBuilder as well.

**Comment by blaketastic2** [comment]
I suppose a work around is to create a filtered query. Is that the recommended approach?

**Comment by sircelsiussexy** [comment]
It does make sense indeed. As far as I know it is not possible at the moment as only Closure filters are allowed.

The Closure form is quite simple and efficient, I'd recommend using that.

I'll see if I can expose FilterBuilder to the `search` method.

**Comment by blaketastic2** [comment]
Yes, I was using the Closure form initially, but I had to many conditional statements that needed to build a dynamic query. My current work around just joins my query and filter in a FilteredQuery, and looks like this:

// merge the Query and Filter
QueryBuilder filteredQuery = QueryBuilders.filteredQuery(queryBuilder, filterBuilder)
// fire off the search...
def res = elasticSearchService.search(searchOptions, filteredQuery, null)

**Comment by sircelsiussexy** [comment]
I added support for `FilterBuilder` objects in the `elasticSearchService.search` method as well as the corresponding injected methods.
