### ISSUE TITLE
Aggregations

### ISSUE THREAD

**Issue by motleycrew** [noamt/elasticsearch-grails-plugin#87]
Hi,

Would it be possible to add some examples in the documentation for performing aggregations using the plugin.

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-metrics-sum-aggregation.html

Thanks,

**Comment by marcos-carceles** [comment]
Hi,

In our project for aggregations we used the `elasticSearchHelper` in combination with the ElasticSearch Java API. The aggregations API is quite exntesive and I believe the plugin does not wrap it (if I'm wrong @noamt , please correct me), I'm afraid doing so might reduce it's flexibility.

This is an example similar to what we used:

```
def index = ...
def baseQuery = ...
def baseFilter = ...
...
elasticSearchHelper.withElasticSearch { Client client ->
                SearchRequestBuilder request = client.prepareSearch(index).setQuery(
                        QueryBuilders.filteredQuery(
                                baseQuery,
                                baseFilter
                        ))

            FilterBuilder aggregationFilter = ... // ie. FilterBuilders.termFilter
            request.addAggregation(
                    AggregationBuilders.filter("myAggregation")
                            .filter(aggregationFilter)
                            .subAggregation(AggregationBuilders.terms("myAggregation")
                                .field("myField"))

            SearchResponse response = request.execute().actionGet()
            InternalFilter filter = response.aggregations.get("myAggregation")
            Terms terms = filter.aggregations.get("myAggregation")
}
```

I'm currently working on trying to simplify using `elasticSearchHelper` and hence the Aggregations API by being able to use the Groovy DSL, but it depends on https://github.com/elasticsearch/elasticsearch-groovy/issues/20.

Let me know if that helped.

**Comment by sircelsiussexy** [comment]
I've been looking at the possibility of adding an optional aggregations parameter to the `search` method of the plugin. I'll come back to you when I've looked into it a bit more.

**Comment by pickypg** [comment]
I've released v1.4.3 and v1.4.4 of the Elasticsearch Groovy client with a Grails compatible jar. Once you add support for it, then you should be able to convert this request:

```json
{
  "query" : {
    "filtered" : {
      "query" : {
        "match" : {
          "field" : "some value"
        }
      },
      "filter" : {
        "term" : {
          "other" : 123
        }
      }
    }
  },
  "aggs" : {
    "myAggregation" : {
      "filter" : { "range" : { "value" : { "gte" : 3 } } },
      "aggs" : {
        "mySubAggregation" : {
          "terms" : { "field" : "myField" }
        }
      }
    }
  }
}
```

into this query/agg using the given Closure:

```groovy
elasticSearchHelper.withElasticSearch {
  SearchResonse response = it.search {
    query {
      filtered {
        query {
          match {
            field = "some value"
          }
        }
        filter {
          term {
            other = 123
          }
        }
      }
    }
    aggs {
      myAggregation {
        filter { range { value { gte = 3 } } }
        aggs {
          mySubAggregation {
            terms { field = myField }
          }
        }
      }
    }
  }.actionGet()

  InternalFilter filter = response.aggregations.get("myAggregation")
  Terms terms = filter.aggregations.get("mySubAggregation")
```

**Comment by sircelsiussexy** [comment]
That should help, thanks a lot!

**Comment by motleycrew** [comment]
I used elasticSearchHelper and it works great! Thank you all.
