### ISSUE TITLE
Failed to resolve dependencies

### ISSUE THREAD

**Issue by catastroof** [noamt/elasticsearch-grails-plugin#91]
I can't use the plugin. I have it since a long time ago but today, it is unavailable.

I use this repo : grailsRepo 'http://repo.grails.org/grails/plugins'

Does there has anything changed?

**Comment by catastroof** [comment]
My version of grails is 2.2.0.

**Comment by sircelsiussexy** [comment]
Can you provide an error log? What version of the plugin are you using?

**Comment by catastroof** [comment]
I use an old version (0.18.7.1-SNAPSHOT). But i've tried with thé 0.0.4.2 (latest on thé grails plugins platform) ans it does the same !

**Comment by sircelsiussexy** [comment]
Can you provide an error log?

**Comment by catastroof** [comment]
This is the output of a grails compile : https://gist.github.com/catastroof/c6962c64cfe342d9baa9

**Comment by noamt** [comment]
Can you provide the error log from a non-snapshot version?

**Comment by catastroof** [comment]
The output with the 0.0.4.3 version : https://gist.github.com/catastroof/763541aa7a33851ce343

**Comment by catastroof** [comment]
I've just tried with a new grails application. I have the same output. It seems like I haven't the good repository in my BuildConfig.groovy.

Does there has anything moved? I don't see another reason…

**Comment by catastroof** [comment]
I have successfully run my app with the plugin version 0.18.7.1-SNAPSHOT (I can't change it for the moment).

What was the problem? The dependency resolver param in the BuildConfig must be set to 'maven'.

Thanks you!

**Comment by catastroof** [comment]
My last comment is false.

The good correction is :

Before :
grailsRepo 'http://repo.grails.org/grails/plugins/'

After :
grailsRepo 'http://grails.org/plugins'
mavenRepo 'http://repo.grails.org/grails/plugins/'

It seems like there was a change in grails plugins repository management.
