### ISSUE TITLE
No Signature error 

### ISSUE THREAD

**Issue by motleycrew** [noamt/elasticsearch-grails-plugin#94]
Hi,

As per documentation http://noamt.github.io/elasticsearch-grails-plugin/guide/searching.html
I should be able to do:

Location.search("${q}") where Location is a Domain class with searchable = true

but I am getting following error

No signature of method: Location.search() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [*xyz*]

I have also noticed that it works sometimes and other times I get above error.

Also, IntelliJ version 14.0.3  doesn't recognise .search method on domain class. 

Any pointers will be helpful.

Thanks,

I am using plugin version 0.4.0.0

**Comment by dawiemalan** [comment]
We've seen the same behaviour. Here's a quick workaround:
Location.search("${q}".toString())

**Comment by motleycrew** [comment]
Thanks @dawiemalan. I tried your suggestion but no luck on my side.

 def query2 = "${q}"
        try {
            results = Location.search(query2.toString())
        } catch (Exception e) {
            log.error(e.message)
        }

I am still getting

Location.search() is applicable for argument types: (java.lang.String) values: [New York]
Possible solutions: each(groovy.lang.Closure), attach(), merge(), refresh(), save(), merge(java.lang.Object)

**Comment by dawiemalan** [comment]
Looks like your Location class is not being injected with dynamic methods. I would check that the plugin is actually loading and that the Location class is searchable. If root=false you won't get dynamic methods.
If still no luck put a breakpoint in DomainDynamicMethodsUtil.injectDynamicMethods and step through the code there.

**Comment by motleycrew** [comment]
@dawiemalan  I restarted my application and everything seems to be working ok. Thanks for your help.
