### ISSUE TITLE
Environment variable

### ISSUE THREAD

**Issue by cesar2502** [noamt/elasticsearch-grails-plugin#95]
I added this line to `BuildConfig.groovy`:

```groovy
runtime ':elasticsearch:0.0.4.4'
```

I run my project and install the plugin, but I get this message:

```shell
Installed plugin elasticsearch-0.0.4.4
The environment variable ELASTIC_SEARCH_HOME specifying the location of ElasticSearch is not set.
Please make sure this variable is set so that the ElasticSearch plugin scripts function correctly.
```
Does any one have any idea how to solve this problem?

Grails 2.4.4
JDK 1.8_20
NetBeans 8.0.2

**Comment by marcos-carceles** [comment]
`ELASTIC_SEARCH_HOME` needs to point to your local elasticsearch installation.

In my dev environment I have added these to my `~/.bashrc`:
```
# ElasticSearch
export ELASTIC_SEARCH_HOME="~/dev/tools/elasticsearch-1.4.5"
export PATH="$ELASTIC_SEARCH_HOME/bin:$PATH"
```

**Comment by puneetbehl** [comment]
Also, you might want to move to `v0.1.0` which is latest version for Grails 2.x.
